#!/usr/bin/python3
import subprocess
import sys
import os
import re
import argparse

def enumerate_subdomains(domain, output_file):
    print(f"<<<Enumerating: {domain}>>>")
    try:
        result = subprocess.run(['sublist3r', '-d', domain], stdout=subprocess.PIPE, stderr=subprocess.PIPE, text=True)
        if result.returncode != 0:
            print(f"Error occurred while enumerating {domain}: {result.stderr.strip()}")
            return
        subdomains = re.findall(r'([a-zA-Z0-9._%+-]+\.{}\.?)'.format(re.escape(domain)), result.stdout)
        if not subdomains:
            print("No subdomains found.")
            return
        for subdomain in subdomains:
            print(subdomain)
            with open(output_file, 'a') as f:
                f.write(subdomain + '\n')
        print("")
    except Exception as e:
        print(f"An error occurred: {e}")
def main(file_path, output_file):
    if not os.path.isfile(file_path):
        print(f"File not found: {file_path}")
        return
    open(output_file, 'w').close()
    with open(file_path, 'r') as f:
        for line in f:
            domain = line.strip()
            if domain:
                enumerate_subdomains(domain, output_file)
    print(f"Subdomain enumeration completed. All results saved in {output_file}.")
if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="Subdomain enumeration using Sublist3r.")
    parser.add_argument("file", help="File containing the list of domains")
    parser.add_argument("-o", "--output", default="subs_sublist3r.txt", help="Specify the output file name (default: subs_sublist3r.txt)")
    args = parser.parse_args()

    main(args.file, args.output)
